"""init tables

Revision ID: 215d31439c3b
Revises: 
Create Date: 2026-03-23 05:31:04.107044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215d31439c3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movie_cd', sa.String(length=20), nullable=False),
    sa.Column('movie_nm', sa.String(length=255), nullable=False),
    sa.Column('movie_nm_en', sa.String(length=255), nullable=True),
    sa.Column('open_dt', sa.Date(), nullable=True),
    sa.Column('rep_genre_nm', sa.String(length=50), nullable=True),
    sa.Column('rep_nation_nm', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('movie_cd'),
    schema='movie'
    )
    op.create_table('person',
    sa.Column('people_cd', sa.String(length=20), nullable=False),
    sa.Column('people_nm', sa.String(length=100), nullable=False),
    sa.Column('people_nm_en', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('people_cd'),
    schema='movie'
    )
    op.create_table('daily_boxoffice',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movie_cd', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('rank_num', sa.Integer(), nullable=True),
    sa.Column('screen_cnt', sa.Integer(), nullable=True),
    sa.Column('screen_share', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('show_cnt', sa.Integer(), nullable=True),
    sa.Column('show_share', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seat_cnt', sa.Integer(), nullable=True),
    sa.Column('seat_share', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seat_sales_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sales_amt', sa.BigInteger(), nullable=True),
    sa.Column('sales_change_dod', sa.BigInteger(), nullable=True),
    sa.Column('audi_cnt', sa.Integer(), nullable=True),
    sa.Column('audi_change_dod', sa.Integer(), nullable=True),
    sa.Column('acc_sales_amt', sa.BigInteger(), nullable=True),
    sa.Column('acc_audi_cnt', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['movie_cd'], ['movie.movie.movie_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_cd', 'target_date', name='uq_daily_boxoffice'),
    schema='movie'
    )
    op.create_table('movie_credit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movie_cd', sa.String(length=20), nullable=False),
    sa.Column('people_cd', sa.String(length=20), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('cast_nm', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['movie_cd'], ['movie.movie.movie_cd'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['people_cd'], ['movie.person.people_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_cd', 'people_cd', 'role_type', name='uq_movie_credit'),
    schema='movie'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_credit', schema='movie')
    op.drop_table('daily_boxoffice', schema='movie')
    op.drop_table('person', schema='movie')
    op.drop_table('movie', schema='movie')
    # ### end Alembic commands ###
