"""add poster_url and synopsis to movie

Revision ID: 3ef5fd1a8996
Revises: da1ed151c6b2
Create Date: 2026-03-26 10:57:09.392436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef5fd1a8996'
down_revision: Union[str, Sequence[str], None] = 'da1ed151c6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('poster_url', sa.String(length=500), nullable=True), schema='movie')
    op.add_column('movie', sa.Column('synopsis', sa.String(), nullable=True), schema='movie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'synopsis', schema='movie')
    op.drop_column('movie', 'poster_url', schema='movie')
    # ### end Alembic commands ###
