"""add chat message table

Revision ID: da1ed151c6b2
Revises: 215d31439c3b
Create Date: 2026-03-25 04:45:23.237850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1ed151c6b2'
down_revision: Union[str, Sequence[str], None] = '215d31439c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_chat_message_session_id'), 'chat_message', ['session_id'], unique=False, schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_chat_message_session_id'), table_name='chat_message', schema='chat')
    op.drop_table('chat_message', schema='chat')
    # ### end Alembic commands ###
